### ISSUE TITLE
8 ) Config 암호화

### ISSUE THREAD

**Issue by yaezzin** [yaezzin/spring-msa-market#8]
## Config 암호화

구성정보들을 한곳에 보아 관리하는 Config Server를 생성하였고, actuator의 refresh를 통해 구성정보들을 모두 업데이트 해주었습니다. 이번에는 데이터베이스 정보 또한 Config Server에 담아두고, 해당 데이터베이스의 비밀번호를 암호화해보도록 하겠습니다.

## 대칭키 비대칭키
스프링 클라우드는 보안을 강화하기 위해 다양한 암호화 및 복호화 방식을 지원합니다. 이 중에서도 스프링 클라우드는 비대칭키와 대칭키 암호화 방식을 지원하고 있습니다.

![Image](https://github.com/user-attachments/assets/ef940ada-2dfb-489e-97b4-63f9069bd677)

대칭키 암호화는 암호화와 복호화에 동일한 키를 사용하는 암호화 방식입니다. 대칭키 암호화 방식은 비교적 간단하고 빠르게 암호화와 복호화를 수행할 수 있어서 속도 측면에서 유리하지만 그러나 키를 안전하게 공유하고 관리해야 하는 한계가 있습니다.

비대칭키 암호화는 공개키 암호화라고도 불리며, 암호화와 복호화에 사용하는 키가 서로 다른 암호화 방식입니다. 비대칭키 암호화에서는 공개키와 개인키라는 두 개의 키가 쌍으로 사용됩니다. 공개키는 모든 사람들이 접근가능한 키로 암호화에 사용되며, 개인키는 복호화에 사용됩니다. 이 방식은 데이터를 안전하게 전송할 수 있고, 공개키를 공개해도 개인키를 알지 못하면 복호화가 불가능하기 때문에 안전한 통신을 보장할 수 있습니다.

앞선 설명에 따르면 물론 당연히 대칭키 방식이 서로 다른 키를 사용하여 암호화/복호화하기 때문에 더 안전합니다. 하지만 토이프로젝트이고, 구현이 더 간단하기 때문에 대칭키 방식을 사용하도록 하겠습니다.

```
encrypt:
  key: abcde # 암호화할 키
```
config-server의 bootstrap.yml에 다음과 같이 추가합니다.

![Image](https://github.com/user-attachments/assets/1946164f-a148-471a-be83-547979dac124)

이후 자신의 비밀번호 텍스트(ex. passwordExample)를 바디에 담아서 /encrypt를 호출해보면 암호화된 내용을 확인할 수 있습니다.

```
#datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:mysql://localhost:3306/[db이름]?useSSL=false 
#    username: [이름]
#    password: [비번]
```
member-service의 database 정보를 모두 주석처리하고, 이 내용을 config server로 이동하도록 하겠습니다.

```
token:
  expiration: 86400000
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:mysql://localhost:3306/{db-name}?useSSL=false
    username: {username}
    password: '{cipher}21e25304c42ec9eb3828e726c10d2fd5235431400edfd49fb2bee84903d2b0d5'
```

해당 내용을 이전에 만들었던 구성정보 레포지토리에 있는 member-dev.yml파일에 넣어주도록하겠습니다. 이떄 {cipher}를 붙여 표시해주고, 그 안에 암호화된 비밀번호를 입력해주었습니다. h2-console에 접속하여 원래의 비밀번호를 입력하더라도 접속이 가능합니다.

![Image](https://github.com/user-attachments/assets/f9d1c543-7de3-4d88-8db9-fff94b228051)

모자이크 했지만, 패스워드가 암호화되지 않은 상태!
이후 localhost:8888/member-dev/default에 접속해보았더니, 패스워드가 암호화되지 않고 그대로 표시되었습니다. 분명 암호화했지만, Spring Cloud Config에서 자동으로 복호화시켜서 응답하기 때문에 원래의 비밀번호가 노출됩니다. 따라서 config-service의 application.yml파일에 spring.cloud.config.server.encrypt.enabled = false로 설정해주었고, 다시 한번 접속해보면 비밀번호가 노출되지 않은 것을 확인할 수 있었습니다.
